[package]
name = "heimdall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "*", features = ["derive"] }
moka = "*"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tokio = { version = "*", features = ["full"] }
wasi-common = "*"
wasmtime = "*"
wasmtime-wasi = "*"

[[bin]]
name = "heimdall"
path = "src/bin/heimdall.rs"
