[package]
name = "bifrost-mongodb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.4.0"
rmp-serde = "1.1.1"
serde = { version = "1.0.147", features = ["derive"] }
